<?php
/**
 * wholesale-data.php — DT Brand's & Jai Hanuman Tex
 * Central Dynamic Wholesale Partners Master Dataset & Resolver
 */

if (!function_exists('getWholesalePartner')) {
    function getWholesalePartnersDataset() {
        return [
            'WHL-8012' => [
                'id' => 'WHL-8012',
                'name' => 'Shree Balaji Textile Emporium',
                'legal_name' => 'Shree Balaji Silk Mills Pvt Ltd',
                'contact' => 'Rameshwar Agarwal',
                'email' => 'balaji.textiles.surat@gmail.com',
                'phone' => '+91 98251 44321',
                'city' => 'Surat, Gujarat',
                'state' => 'Gujarat',
                'address' => 'Plot 42, Millennium Textile Market-2, Ring Road, Surat, Gujarat 395002',
                'tier' => 'Platinum Wholesale (35% Off)',
                'tier_raw' => 'platinum wholesale',
                'tier_short' => 'PLATINUM VIP',
                'tier_badge' => 'gold',
                'margin_pct' => 35,
                'gstin' => '24AAAPL1234F1Z8',
                'pan' => 'AAAPL1234F',
                'structure' => 'Private Limited Company',
                'sanctioned_limit' => 500000,
                'utilized_credit' => 210000,
                'available_credit' => 290000,
                'total_purchase' => 2450000,
                'orders_count' => 64,
                'payment_terms' => 'Net 30 Days',
                'credit_status' => 'Good (₹2.9L Avail)',
                'credit_badge' => 'emerald',
                'verification' => 'Verified KYC',
                'verification_badge' => 'emerald',
                'status' => 'Active',
                'status_type' => 'approved',
                'joined_date' => '14 Oct 2024',
                'initials' => 'SB'
            ],
            'WHL-8013' => [
                'id' => 'WHL-8013',
                'name' => 'Varanasi Weaves & Silks Syndicate',
                'legal_name' => 'Varanasi Weaves Wholesale Hub LLP',
                'contact' => 'Mukesh Chourasia',
                'email' => 'varanasi.weaves@outlook.com',
                'phone' => '+91 98765 88990',
                'city' => 'Varanasi, UP',
                'state' => 'Uttar Pradesh',
                'address' => 'Shop 14, Chowk Silk Mandi, Varanasi, Uttar Pradesh 221001',
                'tier' => 'Platinum Wholesale (35% Off)',
                'tier_raw' => 'platinum wholesale',
                'tier_short' => 'PLATINUM VIP',
                'tier_badge' => 'gold',
                'margin_pct' => 35,
                'gstin' => '09AAACV5678B1Z2',
                'pan' => 'AAACV5678B',
                'structure' => 'Limited Liability Partnership (LLP)',
                'sanctioned_limit' => 300000,
                'utilized_credit' => 120000,
                'available_credit' => 180000,
                'total_purchase' => 1890000,
                'orders_count' => 48,
                'payment_terms' => 'Net 45 Days',
                'credit_status' => 'Good (₹1.8L Avail)',
                'credit_badge' => 'emerald',
                'verification' => 'Verified KYC',
                'verification_badge' => 'emerald',
                'status' => 'Active',
                'status_type' => 'approved',
                'joined_date' => '22 Nov 2024',
                'initials' => 'VW'
            ],
            'WHL-8014' => [
                'id' => 'WHL-8014',
                'name' => 'Jaipur Royal Saree Distributors',
                'legal_name' => 'Royal Saree Hub Rajasthan',
                'contact' => 'Dinesh Shekhawat',
                'email' => 'royal.jaipur@sareehub.in',
                'phone' => '+91 94280 22334',
                'city' => 'Jaipur, Rajasthan',
                'state' => 'Rajasthan',
                'address' => 'B-12, Johari Bazar Textile Complex, Jaipur, Rajasthan 302003',
                'tier' => 'Gold Distributor (28% Off)',
                'tier_raw' => 'gold distributor',
                'tier_short' => 'GOLD VIP',
                'tier_badge' => 'gold',
                'margin_pct' => 28,
                'gstin' => '08AAACR9012D1Z5',
                'pan' => 'AAACR9012D',
                'structure' => 'Partnership Firm',
                'sanctioned_limit' => 200000,
                'utilized_credit' => 120000,
                'available_credit' => 80000,
                'total_purchase' => 1240000,
                'orders_count' => 36,
                'payment_terms' => 'Net 15 Days',
                'credit_status' => 'Good (₹80k Avail)',
                'credit_badge' => 'emerald',
                'verification' => 'Verified KYC',
                'verification_badge' => 'emerald',
                'status' => 'Active',
                'status_type' => 'approved',
                'joined_date' => '05 Jan 2025',
                'initials' => 'JR'
            ],
            'WHL-8015' => [
                'id' => 'WHL-8015',
                'name' => 'Kanchipuram Silk Stockists',
                'legal_name' => 'Kanchi Handloom Stockists Ltd',
                'contact' => 'S. Rajagopalan',
                'email' => 'kanchi.stockists@gmail.com',
                'phone' => '+91 91234 55667',
                'city' => 'Chennai, Tamil Nadu',
                'state' => 'Tamil Nadu',
                'address' => '77 Gandhi Road, Kanchipuram / T. Nagar, Chennai 600017',
                'tier' => 'Silver Bulk Partner (20% Off)',
                'tier_raw' => 'silver bulk partner',
                'tier_short' => 'SILVER BULK',
                'tier_badge' => 'blue',
                'margin_pct' => 20,
                'gstin' => '33AAACK3456E1Z9',
                'pan' => 'AAACK3456E',
                'structure' => 'Public Limited Company',
                'sanctioned_limit' => 50000,
                'utilized_credit' => 0,
                'available_credit' => 50000,
                'total_purchase' => 680000,
                'orders_count' => 18,
                'payment_terms' => 'Advance 50%',
                'credit_status' => 'Normal',
                'credit_badge' => 'blue',
                'verification' => 'Verified KYC',
                'verification_badge' => 'emerald',
                'status' => 'Active',
                'status_type' => 'approved',
                'joined_date' => '18 Feb 2025',
                'initials' => 'KS'
            ],
            'WHL-8016' => [
                'id' => 'WHL-8016',
                'name' => 'Mahalaxmi Silk House Rajkot',
                'legal_name' => 'Mahalaxmi Enterprise',
                'contact' => 'Pravin Solanki',
                'email' => 'mahalaxmi.rajkot@gmail.com',
                'phone' => '+91 98980 11223',
                'city' => 'Rajkot, Gujarat',
                'state' => 'Gujarat',
                'address' => 'Shop 5, Dharmendra Road Saree Market, Rajkot, Gujarat 360001',
                'tier' => 'Bronze Starter (12% Off)',
                'tier_raw' => 'bronze starter',
                'tier_short' => 'BRONZE STARTER',
                'tier_badge' => 'amber',
                'margin_pct' => 12,
                'gstin' => '24AAAPM7890H1Z1',
                'pan' => 'AAAPM7890H',
                'structure' => 'Sole Proprietorship',
                'sanctioned_limit' => 0,
                'utilized_credit' => 0,
                'available_credit' => 0,
                'total_purchase' => 0,
                'orders_count' => 0,
                'payment_terms' => 'Prepaid / Proforma',
                'credit_status' => 'No Credit',
                'credit_badge' => 'amber',
                'verification' => 'Pending Review',
                'verification_badge' => 'amber',
                'status' => 'Pending Review',
                'status_type' => 'pending',
                'joined_date' => '20 Aug 2026',
                'initials' => 'MS'
            ],
            'WHL-8017' => [
                'id' => 'WHL-8017',
                'name' => 'Kolkata Saree Emporium Hub',
                'legal_name' => 'Kolkata Silk Syndicate',
                'contact' => 'Subhashish Ghosh',
                'email' => 'kolkata.emporium@rediffmail.com',
                'phone' => '+91 98310 99887',
                'city' => 'Kolkata, West Bengal',
                'state' => 'West Bengal',
                'address' => '12 Barabazar Cotton Street, Kolkata, West Bengal 700007',
                'tier' => 'Silver Bulk Partner (20% Off)',
                'tier_raw' => 'silver bulk partner',
                'tier_short' => 'SILVER BULK',
                'tier_badge' => 'blue',
                'margin_pct' => 20,
                'gstin' => '19AAACK1122F1Z3',
                'pan' => 'AAACK1122F',
                'structure' => 'Partnership Firm',
                'sanctioned_limit' => 100000,
                'utilized_credit' => 100000,
                'available_credit' => 0,
                'total_purchase' => 450000,
                'orders_count' => 12,
                'payment_terms' => 'Net 30 Days',
                'credit_status' => 'Exhausted (₹0 Avail)',
                'credit_badge' => 'crimson',
                'verification' => 'Verified KYC',
                'verification_badge' => 'emerald',
                'status' => 'Suspended',
                'status_type' => 'suspended',
                'joined_date' => '10 Dec 2024',
                'initials' => 'KS'
            ]
        ];
    }

    function getWholesalePartner($id) {
        $dataset = getWholesalePartnersDataset();
        if (isset($dataset[$id])) {
            return $dataset[$id];
        }
        return $dataset['WHL-8012'];
    }
}
