-- ══════════════════════════════════════════════════════════════════════════
-- Migration: 2026_09_12_000007_create_notifications_admin_tables.sql
-- Description: Section 31 Notification Admin Multi-Channel Schema & Logs
-- DT Brand's & Jai Hanuman Tex
-- ══════════════════════════════════════════════════════════════════════════

-- 1. Notification Templates Table
CREATE TABLE IF NOT EXISTS `notification_templates` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `template_key` VARCHAR(80) NOT NULL UNIQUE,
    `channel` ENUM('whatsapp', 'email', 'sms', 'push', 'in_app') NOT NULL,
    `title` VARCHAR(150) NOT NULL,
    `subject` VARCHAR(255) NULL,
    `category` VARCHAR(50) NOT NULL DEFAULT 'Transactional',
    `content` TEXT NOT NULL,
    `variables_json` LONGTEXT NULL,
    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
    `meta_template_id` VARCHAR(100) NULL,
    `dlt_template_id` VARCHAR(100) NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_nt_channel` (`channel`),
    INDEX `idx_nt_category` (`category`),
    INDEX `idx_nt_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Notification Dispatch & Delivery Logs Table
CREATE TABLE IF NOT EXISTS `notification_logs` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `channel` ENUM('whatsapp', 'email', 'sms', 'push', 'in_app') NOT NULL,
    `recipient` VARCHAR(150) NOT NULL,
    `recipient_name` VARCHAR(100) NULL,
    `template_key` VARCHAR(80) NULL,
    `subject` VARCHAR(255) NULL,
    `message` TEXT NOT NULL,
    `order_id` INT UNSIGNED NULL,
    `status` ENUM('queued', 'sent', 'delivered', 'read', 'failed') NOT NULL DEFAULT 'sent',
    `provider` VARCHAR(50) NOT NULL DEFAULT 'direct',
    `provider_msg_id` VARCHAR(150) NULL,
    `error_message` TEXT NULL,
    `retry_count` INT NOT NULL DEFAULT 0,
    `last_retry_at` DATETIME NULL,
    `metadata_json` LONGTEXT NULL,
    `sent_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `delivered_at` DATETIME NULL,
    INDEX `idx_nl_channel` (`channel`),
    INDEX `idx_nl_status` (`status`),
    INDEX `idx_nl_recipient` (`recipient`),
    INDEX `idx_nl_order` (`order_id`),
    INDEX `idx_nl_sent` (`sent_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Notification Gateway Providers Table
CREATE TABLE IF NOT EXISTS `notification_providers` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `provider_key` VARCHAR(50) NOT NULL UNIQUE,
    `channel` ENUM('whatsapp', 'email', 'sms', 'push') NOT NULL,
    `display_name` VARCHAR(100) NOT NULL,
    `is_enabled` TINYINT(1) NOT NULL DEFAULT 1,
    `config_json` LONGTEXT NULL,
    `status` ENUM('operational', 'degraded', 'error', 'unconfigured') NOT NULL DEFAULT 'operational',
    `last_health_check` DATETIME NULL,
    `last_error` TEXT NULL,
    `latency_ms` INT NOT NULL DEFAULT 45,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_np_channel` (`channel`),
    INDEX `idx_np_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. Seed Standard Templates If Not Exists
INSERT IGNORE INTO `notification_templates` (`template_key`, `channel`, `title`, `subject`, `category`, `content`, `variables_json`, `is_active`, `meta_template_id`, `dlt_template_id`)
VALUES 
('dt_order_placed_wa', 'whatsapp', 'Order Confirmation WhatsApp HSM', NULL, 'Utility', 
 'Namaste {{customer_name}}! 🙏 Your order #{{order_no}} for {{item_count}} handloom items (Total: ₹{{amount}}) has been placed successfully with DT Brand\'s. Our master weavers are packaging your order.', 
 '["customer_name", "order_no", "item_count", "amount"]', 1, 'dt_order_placed_v1', NULL),

('dt_dispatch_tracking_wa', 'whatsapp', 'Order Dispatch Tracking WhatsApp', NULL, 'Utility', 
 'Great news {{customer_name}}! Your parcel for order #{{order_no}} is on its way via {{courier}} (AWB: {{tracking_no}}). Track your shipment here: {{tracking_url}}', 
 '["customer_name", "order_no", "courier", "tracking_no", "tracking_url"]', 1, 'dt_dispatch_tracking_v2', NULL),

('dt_b2b_wholesale_quote_wa', 'whatsapp', 'B2B Wholesale Quotation PDF', NULL, 'Marketing', 
 'Hello {{merchant_name}}, your wholesale lot quotation for {{bale_qty}} sarees has been generated by DT Brand\'s executive desk. View & approve quote: {{quote_url}}', 
 '["merchant_name", "bale_qty", "quote_url"]', 1, 'dt_b2b_wholesale_quote', NULL),

('dt_order_placed_email', 'email', 'Customer Order Invoice Confirmation', 'Order Confirmation #{{order_no}} — DT Brand\'s & Jai Hanuman Tex', 'Transactional', 
 'Dear {{customer_name}}, thank you for your order #{{order_no}}. Amount: ₹{{amount}}. Your authentic Surat handloom weaves are currently being verified.', 
 '["customer_name", "order_no", "amount"]', 1, NULL, NULL),

('dt_dispatch_tracking_email', 'email', 'Shipment Tracking & AWB Notice', 'Your DT Brand\'s Order #{{order_no}} Has Shipped!', 'Transactional', 
 'Dear {{customer_name}}, your order #{{order_no}} has been dispatched with {{courier}}. Tracking AWB: {{tracking_no}}.', 
 '["customer_name", "order_no", "courier", "tracking_no"]', 1, NULL, NULL),

('dt_order_placed_sms', 'sms', 'Order Confirmation SMS', NULL, 'Transactional', 
 'Dear {{customer_name}}, DT Brand order #{{order_no}} of Rs.{{amount}} confirmed. We are processing your handloom shipment. - DTHNTX', 
 '["customer_name", "order_no", "amount"]', 1, NULL, 'DLT_1407161234567'),

('dt_dispatch_sms', 'sms', 'Dispatch Notification SMS', NULL, 'Transactional', 
 'DT Brand order #{{order_no}} dispatched via {{courier}} AWB {{tracking_no}}. Track at {{tracking_url}} - DTHNTX', 
 '["customer_name", "order_no", "courier", "tracking_no", "tracking_url"]', 1, NULL, 'DLT_1407161234568'),

('dt_push_festive_drop', 'push', 'New Festive Weaves Drop', 'Fresh Festive Silk Drop is Live!', 'Marketing', 
 'Explore brand new pure zari Kanjivaram & Banarasi handloom weaves directly from Surat powerlooms with instant festive discounts!', 
 '["discount_pct"]', 1, NULL, NULL);

-- 5. Seed Core Providers If Not Exists
INSERT IGNORE INTO `notification_providers` (`provider_key`, `channel`, `display_name`, `is_enabled`, `config_json`, `status`, `last_health_check`, `latency_ms`)
VALUES
('whatsapp_cloud', 'whatsapp', 'Meta WhatsApp Cloud API', 1, '{"phone_number_id":"1029384756","waba_id":"9876543210","api_version":"v19.0","access_token":"••••••••••••••••"}', 'operational', NOW(), 42),
('smtp_mail', 'email', 'Hostinger Enterprise SMTP', 1, '{"host":"smtp.hostinger.com","port":465,"encryption":"ssl","username":"concierge@jaihanumantex.in","password":"••••••••••••••••"}', 'operational', NOW(), 58),
('msg91_sms', 'sms', 'MSG91 DLT Enterprise SMS', 1, '{"sender_id":"DTHNTX","route":"4","auth_key":"••••••••••••••••"}', 'operational', NOW(), 35),
('fcm_push', 'push', 'Firebase Cloud Messaging (FCM)', 1, '{"project_id":"dt-brands-arniya","server_key":"••••••••••••••••"}', 'operational', NOW(), 28);
